spring.application.name=FeishuSmartBot
# ================= \u98DE\u4E66\u673A\u5668\u4EBA\u914D\u7F6E =================
# \u5E94\u7528\u51ED\u8BC1
feishu.app.id=cli_a909be3353badbc6
feishu.app.secret=7sAZLuJLS54L89vgYpAZygmEiGoy3oQo

# \u591A\u7EF4\u8868\u683C\u914D\u7F6E (App Token + Table IDs)
feishu.bitable.app-token=AMy0bveLpaX3W8sj2Hmc5r3Qnbh
feishu.bitable.table-id.trial=tbltPwNOIy7eYmE8
feishu.bitable.table-id.newbie=tblHSRyFg4qxzuhP
feishu.bitable.table-id.mcp.trial=tbl1hckmWdHK5tQZ

# \u76EE\u6807\u7FA4\u7EC4 ID
feishu.chat.target-id.trial=oc_0f7948ebb455a363938e72e4028d5e9f
feishu.chat.target-id.newbie=oc_5ca41f821ce0679e9e08dbdb83aae7ff
feishu.chat.target-id.mcp.trial=oc_b33203ec40536a07328f8b44d4ae3350